version: "3.3"
services:

  adminer:
    image: arm32v7/adminer
    restart: always
    ports:
      - 8080:8080

  postgres:
    image: arm32v7/postgres
    container_name: "postgres"
    hostname: "postgres"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=ola
      - POSTGRES_DB=ola
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "curl", "-sI", "http://127.0.0.1:5432/ping"]
      interval: 30s
      timeout: 1s
      retries: 24

  homeassistant:
    image: homeassistant/raspberrypi4-homeassistant
    volumes:
      - ./homeassistant:/config
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: unless-stopped
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8123"]
      interval: 30s
      timeout: 10s
      retries: 6
    network_mode: host
