
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

recorder: !include recorder.yaml

speedtestdotnet:
  scan_interval:
    minutes: 60
  monitored_conditions:
    - ping
    - download
    - upload

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret chat_id_1
      - !secret chat_id_2

group: !include include/groups.yaml
automation: !include include/automations.yaml
script: !include include/scripts.yaml
scene: !include include/scenes.yaml
sensor: !include include/sensors.yaml
notify: !include include/notify.yaml
binary_sensor: !include include/binary_sensors.yaml
