- alias: Endret IP addresse
  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.ip
  action:
    service: scripts.telegram_ip_fornyet

- alias: gi IP addresse
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/ip'
  action:
    - service: telegram_bot.send_message
      data_template:
        target: '{{ trigger.event.data.user_id }}'
        message: '{{ states.sensor.ip_addresse.state }}'

- alias: list banned
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/banned'
  action:
    - service: telegram_bot.send_message
      data_template:
        target: '{{ trigger.event.data.user_id }}'
        message: '{{ trigger.event.data.command }}'
   

- alias: Login Failure
  trigger:
    platform: state
    entity_id: persistent_notification.httplogin
  condition:
    condition: template
    value_template: "{{ trigger.to_state.state != off }}"
  action:
    service: notify.ola
    data:
      message: "Failed Home Assistant login attempt!"
  action:
    service: notify.terje
    data:
      message: "Failed Home Assistant login attempt!"

 
- alias: stop router
  trigger:
    platform: state
    entity_id: binary_sensor.online
    to: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.fibaro_system_fgwpe_f_wall_plug_gen5_switch
  - service: timer.start
    entity_id: timer.router_short

- alias: start router
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.router_short
  action:
  - service: switch.turn_on
    entity_id: switch.fibaro_system_fgwpe_f_wall_plug_gen5_switch
  - service: timer.start
    entity_id: timer.router_long


- alias: router restart ip
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.router_long
  action:
  - service: notify.ola
    data:
      message: 'Router restartet, nåværende IP: {{ states.sensor.ip_addresse.state }}'
  - service: notify.terje
    data:
      message: 'Router restartet, nåværende IP: {{ states.sensor.ip_addresse.state }}'
